AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  zendesk
  
  Zendesk integration lambda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Architectures:
      - x86_64

Resources:
  ZendeskIntegrationFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        SQSQueueEvent:
          Type: SQS
          Properties:
            Queue: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:lambda-queue
            BatchSize: 1
    Metadata:
      DockerTag: local
      DockerContext: ./
      Dockerfile: build/Dockerfile

Outputs:
  ZendeskIntegrationFunction:
    Description: "Zendesk integration lambda"
    Value: !GetAtt ZendeskIntegrationFunction.Arn
