name: Build Image
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
          env:
            DOCKER_BUILDKIT: 1
            PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
            BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
            BUF_USER: ${{ secrets.BUF_USER }}
          run: make docker/build
      - name: 
